///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/music.aks
/// Generation time: jue 19 mar 2026 19:36:35 CET
///

/// Song 'music_song' metadata macros
#define music_song_address  0x0500
#define music_song_size     5567
#define music_song_end      0x1ABF

/// Song 'music_song' array declaration
extern void music_song[music_song_size];
