///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/music.aks
/// Generation time: Sun Apr 12 18:54:21 CEST 2026
///

/// Song 'music_song' metadata macros
#define music_song_address  0x0500
#define music_song_size     4793
#define music_song_end      0x17B9

/// Song 'music_song' array declaration
extern void music_song[music_song_size];
