#!/usr/bin/env python3
import sys, os

# Mapping from png2sprite characters (based on hardware index)
# to LOGICAL palette indices in main.c (default_palette[16])
CHAR_MAP = {
    '.': 0,   # HW_BLACK (0)        -> Logical 0
    'S': 12,  # HW_BLUE (1)         -> Logical 12
    'B': 1,   # HW_BRIGHT_BLUE (2)  -> Logical 1
    'r': 8,   # HW_RED (3)          -> Logical 8
    'u': 7,   # HW_MAGENTA (4)      -> Logical 7 (approx)
    'm': 14,  # HW_MAUVE (5)        -> Logical 14
    'R': 3,   # HW_BRIGHT_RED (6)   -> Logical 3
    'p': 3,   # HW_PURPLE (7)       -> Logical 3 (approx)
    'M': 7,   # HW_BRIGHT_MAGENTA (8)-> Logical 7
    'g': 9,   # HW_GREEN (9)        -> Logical 9
    'c': 10,  # HW_CYAN (10)        -> Logical 10
    's': 10,  # HW_SKY_BLUE (11)    -> Logical 10 (approx)
    'l': 15,  # HW_YELLOW (12)      -> Logical 15
    'w': 11,  # HW_WHITE (13)       -> Logical 11
    'b': 12,  # HW_PASTEL_BLUE (14) -> Logical 12 (approx)
    'o': 15,  # HW_ORANGE (15)      -> Logical 15 (approx)
    'k': 11,  # HW_PINK (16)        -> Logical 11 (approx)
    'q': 14,  # HW_PASTEL_MAGENTA (17)-> Logical 14 (approx)
    'G': 5,   # HW_BRIGHT_GREEN (18)-> Logical 5
    'e': 5,   # HW_SEA_GREEN (19)   -> Logical 5 (approx)
    'C': 6,   # HW_BRIGHT_CYAN (20) -> Logical 6
    'i': 5,   # HW_LIME (21)         -> Logical 5 (approx)
    'n': 9,   # HW_PASTEL_GREEN (22)-> Logical 9 (approx)
    't': 10,  # HW_PASTEL_CYAN (23) -> Logical 10 (approx)
    'Y': 4,   # HW_BRIGHT_YELLOW (24)-> Logical 4
    'd': 4,   # HW_PASTEL_YELLOW (25)-> Logical 4 (approx)
    'W': 2,   # HW_BRIGHT_WHITE (26)-> Logical 2
}

def px2byte(p0, p1):
    b = 0
    if p0 & 1: b |= 0x80
    if p1 & 1: b |= 0x40
    if p0 & 4: b |= 0x20
    if p1 & 4: b |= 0x10
    if p0 & 2: b |= 0x08
    if p1 & 2: b |= 0x04
    if p0 & 8: b |= 0x02
    if p1 & 8: b |= 0x01
    return b

def convert(input_txt, output_h, name, trans_char=None):
    with open(input_txt, 'r') as f:
        content = f.read()
    
    start_tag = 'sprite_data = ['
    start = content.find(start_tag)
    if start == -1:
        print(f"Error: could not find sprite_data in {input_txt}")
        return
        
    end = content.find(']', start)
    if end == -1:
        print(f"Error: could not find end of sprite_data in {input_txt}")
        return
    
    end = content.rfind(']')
    data_str = content[start:end+1]
    
    loc = {}
    try:
        exec(data_str, {}, loc)
        sprite_data = loc['sprite_data']
    except Exception as e:
        print(f"Error executing sprite data: {e}")
        return
    
    pixels = []
    for row in sprite_data:
        for i in range(0, len(row), 2):
            c0 = row[i]
            c1 = row[i+1] if i+1 < len(row) else '.'
            
            idx0 = CHAR_MAP.get(c0, 0)
            idx1 = CHAR_MAP.get(c1, 0)
            
            if trans_char is not None:
                mask = 0x00
                if c0 == trans_char:
                    mask |= 0xAA  # P0 bits
                    idx0 = 0      # Transparent pixels must be 0 in sprite byte
                if c1 == trans_char:
                    mask |= 0x55  # P1 bits
                    idx1 = 0
                
                pixels.append(mask)
                pixels.append(px2byte(idx0, idx1))
            else:
                pixels.append(px2byte(idx0, idx1))
    
    width_bytes = (len(sprite_data[0]) + 1) // 2
    height = len(sprite_data)
    
    guard = f"{name.upper()}_H"
    with open(output_h, 'w') as f:
        f.write(f"// Auto-generated by tools/sprite2h.py\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <types.h>\n\n")
        f.write(f"#define {name.upper()}_WIDTH_BYTES {width_bytes}\n")
        f.write(f"#define {name.upper()}_HEIGHT      {height}\n\n")
        f.write(f"// Sprite arrays are interleaved with masks if transparency is enabled\n")
        f.write(f"const u8 {name}_sprite[{len(pixels)}] = {{\n")
        
        bytes_per_row = width_bytes * (2 if trans_char else 1)
        for i, b in enumerate(pixels):
            if i % bytes_per_row == 0:
                f.write("    ")
            f.write(f"0x{b:02x}")
            if i < len(pixels) - 1:
                f.write(", ")
            if (i+1) % bytes_per_row == 0:
                f.write("\n")
        f.write("};\n\n")
        f.write(f"#endif // {guard}\n")
    print(f"Generated: {output_h} ({width_bytes}x{height} pixels, {len(pixels)} bytes, Masked: {trans_char is not None})")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Convert sprite text to C header")
    parser.add_argument("input", help="Input text file from png2sprite.py")
    parser.add_argument("output", help="Output C header file (.h)")
    parser.add_argument("name", help="Name prefix for the sprite variable")
    parser.add_argument("--transparent", help="Character to use as transparent mask (e.g. '.')", default=None)
    
    args = parser.parse_args()
    convert(args.input, args.output, args.name, args.transparent)
